# -*- coding: utf-8 -*-
"""English US keymap, revised 2019-11-18 by Adam Twardoch."""
from __future__ import unicode_literals

keymap = {
    "click": "click",
    "double-click": "2×click",
    "drag": "drag",
    "drag-drop": "drag-drop",
    "menu-button": "☰",
    "close-button": "✕",
    "gear-button": "☼",
    "update-button": "↻",
    "auto-button": "♥",
    "turn-on": "✓",
    "turn-off": "□",
    "mac": '<sup>M</sup>',
    "win": '<sup>W</sup>',

    # Digits
    "0": "0",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",

    # Letters
    "a": "A",
    "b": "B",
    "c": "C",
    "d": "D",
    "e": "E",
    "f": "F",
    "g": "G",
    "h": "H",
    "i": "I",
    "j": "J",
    "k": "K",
    "l": "L",
    "m": "M",
    "n": "N",
    "o": "O",
    "p": "P",
    "q": "Q",
    "r": "R",
    "s": "S",
    "t": "T",
    "u": "U",
    "v": "V",
    "w": "W",
    "x": "X",
    "y": "Y",
    "z": "Z",

    # Space
    "space": "<small>Space</small>",

    # Punctuation
    "backslash": "\\",
    "bar": "|",
    "brace-left": "{",
    "brace-right": "}",
    "bracket-left": "[",
    "bracket-right": "]",
    "colon": ":",
    "comma": ",",
    "double-quote": "\"",
    "equal": "=",
    "exclam": "!",
    "grave": "`",
    "greater": ">",
    "less": "<",
    "minus": "-",
    "period": ".",
    "plus": "+",
    "question": "?",
    "semicolon": ";",
    "single-quote": "'",
    "slash": "/",
    "tilde": "~",
    "underscore": "_",

    # Navigation keys
    "arrow": "↑↓←→",
    "arrow-up-down": "↑↓",
    "arrow-left-right": "←→",
    "arrow-up": "↑",
    "arrow-down": "↓",
    "arrow-left": "←",
    "arrow-right": "→",
    "page-up": "<small>Pg</small>U<small>p</small>",
    "page-down": "<small>Pg</small>D<small>n</small>",
    "home": "<small>Home</small>",
    "end": "<small>End</small>",

    # Edit keys
    "backspace": "<small>BkSp</small>",
    "delete": "<small>Del</small>",
    "insert": "<small>Ins</small>",
    "tab": "⇥",

    # Action keys
    "break": "<small>Break</small>",
    "caps-lock": "<small>CapsLock</small>",
    "clear": "<small>Clear</small>",
    "eject": "<small>Eject</small>",
    "enter": "↩",
    "escape": "<small>Esc</small>",
    "help": "<small>Help</small>",
    "print-screen": "<small>Prt</small>S<small>c</small>",
    "scroll-lock": "<small>Scr</small>L<small>ock</small>",

    # Numeric keypad
    "num0": "<small>Num</small> 0",
    "num1": "<small>Num</small> 1",
    "num2": "<small>Num</small> 2",
    "num3": "<small>Num</small> 3",
    "num4": "<small>Num</small> 4",
    "num5": "<small>Num</small> 5",
    "num6": "<small>Num</small> 6",
    "num7": "<small>Num</small> 7",
    "num8": "<small>Num</small> 8",
    "num9": "<small>Num</small> 9",
    "num-asterisk": "<small>Num</small> *",
    "num-clear": "<small>Num</small> C<small>lear</small>",
    "num-delete": "<small>Num</small> D<small>el</small>",
    "num-equal": "<small>Num</small> =",
    "num-lock": "<small>Num</small>L<small>ock</small>",
    "num-minus": "<small>Num</small> -",
    "num-plus": "<small>Num</small> +",
    "num-separator": "<small>Num</small> .",
    "num-slash": "<small>Num</small> /",
    "num-enter": "<small>Num</small> E<small>nter</small>",

    # Modifier keys
    "alt": "<small>Alt</small>",
    "command": "<small>Cmd</small>",
    "control": "<small>Ctrl</small>",
    "function": "<small>Fn</small>",
    "left-alt": "Left <small>Alt</small>",
    "left-control": "Left <small>Ctrl</small>",
    "left-shift": "Left <small>Shift</small>",
    "left-windows": "Left <small>Win</small>",
    "meta": "<small>Meta</small>",
    "option": "<small>Opt</small>",
    "right-alt": "Right <small>Alt</small>",
    "right-control": "Right <small>Ctrl</small>",
    "right-shift": "Right <small>Shift</small>",
    "right-windows": "Right <small>Win</small>",
    "shift": "<small>Shift</small>",
    "windows": "<small>Win</small>",

    # Function keys
    "f1": "F1",
    "f2": "F2",
    "f3": "F3",
    "f4": "F4",
    "f5": "F5",
    "f6": "F6",
    "f7": "F7",
    "f8": "F8",
    "f9": "F9",
    "f10": "F10",
    "f11": "F11",
    "f12": "F12",
    "f13": "F13",
    "f14": "F14",
    "f15": "F15",
    "f16": "F16",
    "f17": "F17",
    "f18": "F18",
    "f19": "F19",
    "f20": "F20",
    "f21": "F21",
    "f22": "F22",
    "f23": "F23",
    "f24": "F24",

    # Extra keys
    "backtab": "Back Tab",
    "browser-back": "Browser Back",
    "browser-favorites": "Browser Favorites",
    "browser-forward": "Browser Forward",
    "browser-home": "Browser Home",
    "browser-refresh": "Browser Refresh",
    "browser-search": "Browser Search",
    "browser-stop": "Browser Stop",
    "context-menu": "Context Menu",
    "copy": "Copy",
    "mail": "Mail",
    "media": "Media",
    "media-next-track": "Next Track",
    "media-pause": "Pause",
    "media-play": "Play",
    "media-play-pause": "Play/Pause",
    "media-prev-track": "Previous Track",
    "media-stop": "Stop",
    "print": "Print",
    "reset": "Reset",
    "select": "Select",
    "sleep": "Sleep",
    "volume-down": "Volume Down",
    "volume-mute": "Mute",
    "volume-up": "Volume Up",
    "zoom": "Zoom",

    # Mouse
    "left-button": "Left Button",
    "middle-button": "Middle Button",
    "right-button": "Right Button",
    "x-button1": "X Button 1",
    "x-button2": "X Button 2"
}

aliases = {
    "\\": "backslash",
    "|": "bar",
    "{": "brace-left",
    "}": "brace-right",
    "[": "bracket-left",
    "]": "bracket-right",
    ":": "colon",
    ",": "comma",
    "''": "double-quote",
    "=": "equal",
    "!": "exclam",
    "`": "grave",
    ">": "greater",
    "<": "less",
    "-": "minus",
    ".": "period",
    "+": "plus",
    "?": "question",
    ";": "semicolon",
    "'": "single-quote",
    "/": "slash",
    "~": "tilde",
    "_": "underscore",
    "add": "num-plus",
    "apps": "context-menu",
    "back": "backspace",
    "bksp": "backspace",
    "bktab": "backtab",
    "cancel": "break",
    "capital": "caps-lock",
    "close-brace": "brace-right",
    "close-bracket": "bracket-right",
    "clr": "clear",
    "cmd": "command",
    "cplk": "caps-lock",
    "ctrl": "control",
    "dblquote": "double-quote",
    "decimal": "num-separator",
    "del": "delete",
    "divide": "num-slash",
    "down": "arrow-down",
    "esc": "escape",
    "return": "enter",
    "exclamation": "exclam",
    "favorites": "browser-favorites",
    "fn": "function",
    "forward": "browser-forward",
    "grave-accent": "grave",
    "greater-than": "greater",
    "gt": "greater",
    "hyphen": "minus",
    "ins": "insert",
    "lalt": "left-alt",
    "launch-mail": "mail",
    "launch-media": "media",
    "lbutton": "left-button",
    "lcontrol": "left-control",
    "lctrl": "left-control",
    "left": "arrow-left",
    "left-ctrl": "left-control",
    "left-menu": "left-alt",
    "left-win": "left-windows",
    "less-than": "less",
    "lmenu": "left-alt",
    "lshift": "left-shift",
    "lt": "less",
    "lwin": "left-windows",
    "mbutton": "middle-button",
    "multiply": "num-asterisk",
    "mute": "volume-mute",
    "next": "page-down",
    "next-track": "media-next-track",
    "num-del": "num-delete",
    "numlk": "num-lock",
    "open-brace": "brace-left",
    "open-bracket": "bracket-left",
    "opt": "option",
    "page-dn": "page-down",
    "page-up": "page-up",
    "pause": "media-pause",
    "pg-dn": "page-down",
    "pg-up": "page-up",
    "pipe": "bar",
    "play": "media-play",
    "play-pause": "media-play-pause",
    "prev-track": "media-prev-track",
    "prior": "page-up",
    "prtsc": "print-screen",
    "question-mark": "question",
    "ralt": "right-alt",
    "rbutton": "right-button",
    "rcontrol": "right-control",
    "rctrl": "right-control",
    "refresh": "browser-refresh",
    "right": "arrow-right",
    "right-ctrl": "right-control",
    "right-menu": "right-alt",
    "right-win": "right-windows",
    "rmenu": "right-alt",
    "rshift": "right-shift",
    "rwin": "right-windows",
    "scroll": "scroll-lock",
    "search": "browser-search",
    "separator": "num-separator",
    "spc": "space",
    "stop": "media-stop",
    "subtract": "num-minus",
    "tabulator": "tab",
    "up": "arrow-up",
    "vol-down": "volume-down",
    "vol-mute": "volume-mute",
    "vol-up": "volume-up",
    "win": "windows",
    "xbutton1": "x-button1",
    "xbutton2": "x-button2",
    "left-brace": "brace-left",
    "right-brace": "brace-right",
    "left-bracket": "bracket-left",
    "right-bracket": "bracket-left"
}
