[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311']
# include = '\.pyi?$'
# exclude = '''
# /(
#    \.eggs
#  | \.git
#  | \.hg
#  | \.mypy_cache
#  | \.tox
#  | \.venv
#  | _build
#  | buck-out
#  | build
#  | dist
# )/
# '''

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests",
]
# Add other pytest configurations if needed
filterwarnings = [
    "ignore::DeprecationWarning",
]
